url: "https://www.faithful3d.team"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "de"
    values:
      layout: "default_de"
  - scope:
      path: "fr"
    values:
      layout: "default_fr"
  - scope:
      path: "pl"
    values:
      layout: "default_pl"
  - scope:
      path: "article"
    values:
      layout: "article"
  - scope:
      path: "credits"
    values:
      layout: "credits"
